icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"

[icons]
icons = "material-nf"

[[block]]
block = "disk_space"
path = "/"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2)"
format_alt = " $icon_swap $swap_used_percents"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
