# modules
source ~/.dotfiles/zsh/aliases.zsh
source ~/.dotfiles/zsh/bindings.zsh
source ~/.dotfiles/zsh/colors.zsh
source ~/.dotfiles/zsh/completion.zsh
source ~/.dotfiles/zsh/exports.zsh
source ~/.dotfiles/zsh/functions.zsh
source ~/.dotfiles/zsh/options.zsh
source ~/.dotfiles/zsh/plugins.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
